#index:
#    path: /
#    controller: App\Controller\DefaultController::index

greetings:
  path: /
  controller: App\Controller\GreetingsController::index


greetings2:
  path: /introduction
  controller: App\Controller\GreetingsController::index2